# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f58620a4acb9c4b8dbed8c14b7d1d6599738f903cc8fdad3e5a7faac494b21c084e2393be79c346ecd356baed78ece173a0ed4d11237c44a04fd855fce77e9b

test:
  secret_key_base: c5187b6f965a5d384b644edc43a9685e75f61ea6712857a1bf60d84304393e62ddb7963de524d0a7ec4d5d0150b37ea177dcee79bffd037469eeb730f575ef2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
